describe('Reviews', function() {

  describe('When logged in', function() {
    beforeEach(function() {
      cy.request('POST', `${Cypress.env('BACKEND')}/testing/reset`)
      cy.task('db:seedUsers')
      cy.login({ email: 'regular@gmail.com', password: 'password' })
    })

    it('user can create a review from movieslists menu', function() {
      cy.get('.MuiGrid-container').find('.MuiIconButton-root').first().click()
      cy.contains('Create a review').click()
      cy.get('input[value=9]').click({ force: true })
      cy.get('#review_text').type('Excellent movie that I have to watch again.')
      cy.get('#create-review').click()
      cy.wait(500)
      cy.get('#my-reviews').click({ force: true })
      cy.contains('Your reviews')
      cy.get('.MuiBox-root').find('.MuiFormControl-root').should('have.length', 2)
      cy.get('.MuiGrid-container').find('.MuiGrid-item').should('have.length', 1)
      cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').should('exist')
      cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').should('contain', 9)
      cy.get('.MuiGrid-container').find('.MuiCardActions-root').find('svg').click({ force: true })
      cy.contains('Excellent movie that I have to watch again.')
    })

    it('user can create a review from detailed movie view and it\'s added to latest reviews', function() {
      cy.get('.MuiGrid-container').find('.MuiGrid-item').first().click()
      cy.get('.MuiGrid-container').find('[aria-label="Create a review"]').click()
      cy.get('input[value=9]').click({ force: true })
      cy.get('#review_text').type('Excellent movie that I have to watch again.')
      cy.get('#create-review').click()
      cy.wait(500)
      cy.contains('Latest reviews')
      cy.contains('Rating: 9')
      cy.contains('Excellent movie that I have to watch again.')
      cy.get('.MuiGrid-container').find('[aria-label="Create a review"]').should('not.exist')
      cy.get('.MuiGrid-container').find('[aria-label="Edit review"]').should('exist')
      cy.get('#my-reviews').click({ force: true })
      cy.contains('Your reviews')
      cy.get('.MuiBox-root').find('.MuiFormControl-root').should('have.length', 2)
      cy.get('.MuiGrid-container').find('.MuiGrid-item').should('have.length', 1)
      cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').should('exist')
      cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').should('contain', 9)
      cy.get('.MuiGrid-container').find('.MuiCardActions-root').find('svg').click({ force: true })
      cy.contains('Excellent movie that I have to watch again.')
    })

    describe('and movie is already reviewed', function() {
      beforeEach(function() {
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').first().click()
        cy.contains('Create a review').click()
        cy.get('input[value=9]').click({ force: true })
        cy.get('#review_text').type('Excellent movie that I have to watch again.')
        cy.get('#create-review').click()
        cy.wait(500)
      })

      it('user can edit review from movieslists menu', function() {
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').first().click()
        cy.contains('Edit review').click()
        cy.get('input[value=7]').click({ force: true })
        cy.get('#review_text').clear()
        cy.get('#review_text').type('Not as good as I remembered.')
        cy.get('#edit-review').click()
        cy.wait(500)
        cy.get('#my-reviews').click({ force: true })
        cy.contains('Your reviews')
        cy.get('.MuiBox-root').find('.MuiFormControl-root').should('have.length', 2)
        cy.get('.MuiGrid-container').find('.MuiGrid-item').should('have.length', 1)
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').should('exist')
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').should('contain', 7)
        cy.get('.MuiGrid-container').find('.MuiCardActions-root').find('svg').click({ force: true })
        cy.contains('Not as good as I remembered.')
        cy.get('html').should('not.contain', 'Excellent movie that I have to watch again.')
      })

      it('user can edit review from detailed movie view and it\'s updated in latest reviews', function() {
        cy.get('.MuiGrid-container').find('.MuiGrid-item').first().click()
        cy.get('.MuiGrid-container').find('[aria-label="Edit review"]').last().click()
        cy.get('input[value=7]').click({ force: true })
        cy.get('#review_text').clear()
        cy.get('#review_text').type('Not as good as I remembered.')
        cy.get('#edit-review').click()
        cy.wait(500)
        cy.contains('Latest reviews')
        cy.contains('Rating: 7')
        cy.contains('Not as good as I remembered.')
        cy.get('html').should('not.contain', 'Excellent movie that I have to watch again.')
        cy.get('.MuiGrid-container').find('[aria-label="Create a review"]').should('not.exist')
        cy.get('.MuiGrid-container').find('[aria-label="Edit review"]').should('exist')
        cy.get('#my-reviews').click({ force: true })
        cy.contains('Your reviews')
        cy.get('.MuiBox-root').find('.MuiFormControl-root').should('have.length', 2)
        cy.get('.MuiGrid-container').find('.MuiGrid-item').should('have.length', 1)
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').should('exist')
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').should('contain', 7)
        cy.get('.MuiGrid-container').find('.MuiCardActions-root').find('svg').click({ force: true })
        cy.contains('Not as good as I remembered.')
        cy.get('html').should('not.contain', 'Excellent movie that I have to watch again.')
      })

      it('user can edit review from the star icon in my reviews view', function() {
        cy.get('#my-reviews').click({ force: true })
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').click()
        cy.get('input[value=7]').click({ force: true })
        cy.get('#review_text').clear()
        cy.get('#review_text').type('Not as good as I remembered.')
        cy.get('#edit-review').click()
        cy.wait(500)
        cy.contains('Your reviews')
        cy.get('.MuiBox-root').find('.MuiFormControl-root').should('have.length', 2)
        cy.get('.MuiGrid-container').find('.MuiGrid-item').should('have.length', 1)
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').should('exist')
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').should('contain', 7)
        cy.get('.MuiGrid-container').find('.MuiCardActions-root').find('svg').click({ force: true })
        cy.contains('Not as good as I remembered.')
        cy.get('html').should('not.contain', 'Excellent movie that I have to watch again.')
      })

      it('user can delete review from movieslists menu', function() {
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').first().click()
        cy.contains('Edit review').click()
        cy.get('#delete-review').click()
        cy.get('#delete-confirm').find('button').last().click()
        cy.wait(500)
        cy.get('#my-reviews').click({ force: true })
        cy.contains('You have not reviewed any movies yet')
        cy.get('.MuiBox-root').find('.MuiFormControl-root').should('not.exist')
        cy.get('.MuiGrid-container').should('not.exist')
        cy.get('html').should('not.contain', 'Excellent movie that I have to watch again.')
      })

      it('user can delete review from detailed movie view and latest reviews updates', function() {
        cy.get('.MuiGrid-container').find('.MuiGrid-item').first().click()
        cy.get('.MuiGrid-container').find('[aria-label="Edit review"]').last().click()
        cy.get('#delete-review').click()
        cy.get('#delete-confirm').find('button').last().click()
        cy.wait(500)
        cy.get('html').should('not.contain', 'Latest reviews')
        cy.get('html').should('not.contain', 'Rating: 9')
        cy.get('html').should('not.contain', 'Excellent movie that I have to watch again.')
        cy.get('#my-reviews').click({ force: true })
        cy.contains('You have not reviewed any movies yet')
        cy.get('.MuiBox-root').find('.MuiFormControl-root').should('not.exist')
        cy.get('.MuiGrid-container').should('not.exist')
        cy.get('html').should('not.contain', 'Excellent movie that I have to watch again.')
      })

      it('user can delete review from the star icon in my reviews view', function() {
        cy.get('#my-reviews').click({ force: true })
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').click()
        cy.get('#delete-review').click()
        cy.get('#delete-confirm').find('button').last().click()
        cy.wait(500)
        cy.contains('You have not reviewed any movies yet')
        cy.get('.MuiBox-root').find('.MuiFormControl-root').should('not.exist')
        cy.get('.MuiGrid-container').should('not.exist')
        cy.get('html').should('not.contain', 'Excellent movie that I have to watch again.')
      })

    })

    describe('and user has reviewed a movie', function() {
      beforeEach(function() {
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').first().click()
        cy.contains('Create a review').click()
        cy.get('input[value=1]').click({ force: true })
        cy.get('#review_text').type('This movie is !¤#$¤#%!&#¤%#!')
        cy.get('#create-review').click()
      })

      it('moderator can access users reviews', function() {
        cy.login({ email: 'moderator@gmail.com', password: 'password' })
        cy.get('#users').click({ force: true })
        cy.contains('User management')
        cy.get('.MuiDataGrid-main').find('[data-rowindex="1"]').find('[data-field="reviews"]').click()
        cy.contains('Reviews of user')
        cy.get('.MuiBox-root').find('.MuiFormControl-root').should('have.length', 2)
        cy.get('.MuiGrid-container').find('.MuiGrid-item').should('have.length', 1)
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').should('exist')
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').should('contain', 1)
        cy.get('.MuiGrid-container').find('.MuiCardActions-root').find('svg').click({ force: true })
        cy.contains('This movie is !¤#$¤#%!&#¤%#!')
      })

      it('moderator can edit users review', function() {
        cy.login({ email: 'moderator@gmail.com', password: 'password' })
        cy.get('#users').click({ force: true })
        cy.contains('User management')
        cy.get('.MuiDataGrid-main').find('[data-rowindex="1"]').find('[data-field="reviews"]').click()
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').click()
        cy.get('#review_text').clear()
        cy.get('#review_text').type('This movie is terrible')
        cy.get('#edit-review').click()
        cy.wait(500)
        cy.contains('Reviews of user')
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').should('exist')
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').should('contain', 1)
        cy.get('.MuiGrid-container').find('.MuiCardActions-root').find('svg').click({ force: true })
        cy.contains('This movie is terrible')
      })

      it('moderator can delete users review', function() {
        cy.login({ email: 'moderator@gmail.com', password: 'password' })
        cy.get('#users').click({ force: true })
        cy.contains('User management')
        cy.get('.MuiDataGrid-main').find('[data-rowindex="1"]').find('[data-field="reviews"]').click()
        cy.get('.MuiGrid-container').find('.MuiIconButton-root').find('p').click()
        cy.get('#delete-review').click()
        cy.get('#delete-confirm').find('button').last().click()
        cy.wait(500)
        cy.get('.MuiGrid-container').should('not.exist')
        cy.get('html').should('not.contain', 'This movie is !¤#$¤#%!&#¤%#!')
      })

    })

  })

})